### ISSUE TITLE
DHT sensor causing Guru Meditation Error 

### ISSUE THREAD

**Issue by lpgn** [fabfarm/ESPlash#40]
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1). 

Core  1 register dump:
PC      : 0x400d7d20  PS      : 0x00060135  A0      : 0x800d7df8  A1      : 0x3ffd41b0  
A2      : 0x00022165  A3      : 0x00000001  A4      : 0x3ffc4978  A5      : 0xdacae800  
A6      : 0x00000000  A7      : 0x40404040  A8      : 0x00027100  A9      : 0x00022165  
A10     : 0x00000001  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x00200000  
A14     : 0x00000028  A15     : 0x00000001  SAR     : 0x00000015  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x40084a05  LEND    : 0x40084a0d  LCOUNT  : 0x00000027  

Backtrace: 0x400d7d1d:0x3ffd41b0 0x400d7df5:0x3ffd41d0 0x400d7e85:0x3ffd4330 0x400d43a2:0x3ffd4360 0x400d43f9:0x3ffd4390 0x400d6d72:0x3ffd43b0 0x4018ec67:0x3ffd4430 0x400df475:0x3ffd4450 0x400dd029:0x3ffd44a0 0x400dd139:0x3ffd44f0 0x400dd321:0x3ffd4540 0x4017434d:0x3ffd4560 0x401743c9:0x3ffd4590 0x40174bae:0x3ffd4�

By disabling temperature and humidity read error disappears.

**Comment by lpgn** [comment]
addr2line -e .pio/build/esp32doit
-devkit-v1/firmware.elf -a -f 0x400d7d1d:0x3ffd41b0 0x400d7df5:0x3ffd41d0 0x400d7e85:0x3ffd4330 0x400d43a2:0x3ffd4360 0x400d43f9:0x3ffd4390 0x400d6d72:0x3ffd43b0 0x4018ec67:0x3ffd4430 0x400df475:0x3ffd4450 0x400dd029:0x3ffd44a0 0x400dd139:0x3ffd44f0 0x400dd321:0x3ffd4540 0x4017434d:0x3ffd4560 0x401743c9:0x3ffd4590 0x40174bae:0x3ffd4
0x400d7d1d
_ZN3DHT11expectPulseEb
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/.pio/libdeps/esp32doit-devkit-v1/DHT sensor library/DHT.cpp:388
0x400d7df5
_ZN3DHT4readEb
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/.pio/libdeps/esp32doit-devkit-v1/DHT sensor library/DHT.cpp:306
0x400d7e85
_ZN3DHT15readTemperatureEbb
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/.pio/libdeps/esp32doit-devkit-v1/DHT sensor library/DHT.cpp:88
0x400d43a2
_Z11readDHTDatab
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/src/fabfarm_irrigation/SetupSensors.cpp:22
0x400d43f9
_Z18readDHTTemperaturev
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/src/fabfarm_irrigation/SetupSensors.cpp:44
0x400d6d72
_Z24handleGetDataJsonRequestP21AsyncWebServerRequest
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/src/fabfarm_irrigation/WebServerManager.cpp:24
0x4018ec67
_ZNSt17_Function_handlerIFvP21AsyncWebServerRequestEPS2_E9_M_invokeERKSt9_Any_dataOS1_
/home/lpgn/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/std_function.h:297
0x400df475
_ZNKSt8functionIFvP21AsyncWebServerRequestEEclES1_
/home/lpgn/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/std_function.h:687
0x400dd029
_ZN21AsyncWebServerRequest10_parseLineEv
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/.pio/libdeps/esp32doit-devkit-v1/ESP Async WebServer/src/WebRequest.cpp:581 (discriminator 1)
0x400dd139
_ZN21AsyncWebServerRequest7_onDataEPvj
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/.pio/libdeps/esp32doit-devkit-v1/ESP Async WebServer/src/WebRequest.cpp:123
0x400dd321
_ZNSt17_Function_handlerIFvPvP11AsyncClientS0_jEZN21AsyncWebServerRequestC4EP14AsyncWebServerS2_EUlS0_S2_S0_jE6_E9_M_invokeERKSt9_Any_dataOS0_OS2_SC_Oj
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/.pio/libdeps/esp32doit-devkit-v1/ESP Async WebServer/src/WebRequest.cpp:76
0x4017434d
_ZNKSt8functionIFvPvP11AsyncClientS0_jEEclES0_S2_S0_j
/home/lpgn/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/std_function.h:687
0x401743c9
_ZN11AsyncClient7_s_recvEPvP7tcp_pcbP4pbufa
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/.pio/libdeps/esp32doit-devkit-v1/AsyncTCP/src/AsyncTCP.cpp:1191
0x40174bae
_ZL19_async_service_taskPv
/home/lpgn/gits_go_here_wsl/E-SPlash/Firmware/.pio/libdeps/esp32doit-devkit-v1/AsyncTCP/src/AsyncTCP.cpp:159

**Comment by WingCode** [comment]
Might be related to https://github.com/adafruit/DHT-sensor-library/issues/211
